dependencies {
    api 'org.testcontainers:testcontainers'
    api project(':testcontainers-redis-common')
    api project(':testcontainers-redis-enterprise-common')
    api libs.redis.enterprise.admin
    testImplementation libs.lettucemod
    testImplementation project(':testcontainers-redis-test')
}