rootProject.name = 'testcontainers-redis'

include 'testcontainers-memcached',
        'testcontainers-redis',
        'testcontainers-redis-common',
        'testcontainers-redis-enterprise',
        'testcontainers-redis-enterprise-common',
        'testcontainers-redis-test'

rootProject.children.each { module ->
    module.projectDir = file("subprojects/${module.name}")
    module.buildFileName = "${module.name}.gradle"
}
