dependencies {
    api 'org.testcontainers:testcontainers'
    api project(':testcontainers-redis-common')
    testImplementation 'org.awaitility:awaitility'
    testImplementation libs.lettucemod
    testImplementation project(':testcontainers-redis-test')
}

eclipse {
    project {
        name = 'testcontainers-redis-core'
    }
}